### ISSUE TITLE
DescriptorRegistry does not know about type [smoketest.ExecutedHttpRequestTest]

### ISSUE THREAD

**Issue by kdeenkhoorn** [xebialabs-community/xld-smoke-test-plugin#3]
Dear All,

When i use this plugin i get the following error when i try to deploy an application with the xldeploy jenkins plugin 7.5.5 on XL Deploy version 8.0.8:

```
hudson.remoting.ProxyException: java.lang.IllegalArgumentException: DescriptorRegistry does not know about type [smoketest.ExecutedHttpRequestTest]
	at com.xebialabs.deployit.booter.remote.RemoteDescriptorRegistry._getDescriptor(RemoteDescriptorRegistry.java:56)
	at com.xebialabs.deployit.plugin.api.reflect.DescriptorRegistry.getDescriptor(DescriptorRegistry.java:128)
	at com.xebialabs.deployit.plugin.api.reflect.Type.getDescriptor(Type.java:64)
	at com.xebialabs.xltype.serialization.ConfigurationItemConverter.readCi(ConfigurationItemConverter.java:194)
	at com.xebialabs.xltype.serialization.xstream.XStreamCiConverter.unmarshal(XStreamCiConverter.java:30)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
Caused: hudson.remoting.ProxyException: com.thoughtworks.xstream.converters.ConversionException: DescriptorRegistry does not know about type [smoketest.ExecutedHttpRequestTest] : DescriptorRegistry does not know about type [smoketest.ExecutedHttpRequestTest]
---- Debugging information ----
message             : DescriptorRegistry does not know about type [smoketest.ExecutedHttpRequestTest]
cause-exception     : java.lang.IllegalArgumentException
cause-message       : DescriptorRegistry does not know about type [smoketest.ExecutedHttpRequestTest]
class               : com.xebialabs.deployit.plugin.api.udm.ConfigurationItem
required-type       : com.xebialabs.deployit.plugin.api.udm.ConfigurationItem
converter-type      : com.xebialabs.deployit.booter.remote.xml.RemoteXStreamCiConverter
path                : /deployment/deployeds/smoketest.ExecutedHttpRequestTest
line number         : 16
class[1]            : com.xebialabs.deployit.engine.api.dto.Deployment
converter-type[1]   : com.xebialabs.xltype.serialization.xstream.DeploymentConverter
version             : not available
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.xebialabs.xltype.serialization.xstream.Converters.readList(Converters.java:21)
	at com.xebialabs.xltype.serialization.xstream.DeploymentConverter.unmarshal(DeploymentConverter.java:83)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1189)
	at com.xebialabs.xltype.serialization.xstream.XStreamReaderWriter.read(XStreamReaderWriter.java:149)
	at com.xebialabs.xltype.serialization.xstream.XStreamReaderWriter.readFrom(XStreamReaderWriter.java:143)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:61)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:53)
	at org.jboss.resteasy.plugins.interceptors.encoding.GZIPDecodingInterceptor.aroundReadFrom(GZIPDecodingInterceptor.java:59)
	at org.jboss.resteasy.core.interception.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:55)
	at org.jboss.resteasy.client.core.BaseClientResponse.readFrom(BaseClientResponse.java:448)
Caused: hudson.remoting.ProxyException: org.jboss.resteasy.spi.ReaderException: com.thoughtworks.xstream.converters.ConversionException: DescriptorRegistry does not know about type [smoketest.ExecutedHttpRequestTest] : DescriptorRegistry does not know about type [smoketest.ExecutedHttpRequestTest]
---- Debugging information ----
message             : DescriptorRegistry does not know about type [smoketest.ExecutedHttpRequestTest]
cause-exception     : java.lang.IllegalArgumentException
cause-message       : DescriptorRegistry does not know about type [smoketest.ExecutedHttpRequestTest]
class               : com.xebialabs.deployit.plugin.api.udm.ConfigurationItem
required-type       : com.xebialabs.deployit.plugin.api.udm.ConfigurationItem
converter-type      : com.xebialabs.deployit.booter.remote.xml.RemoteXStreamCiConverter
path                : /deployment/deployeds/smoketest.ExecutedHttpRequestTest
line number         : 16
class[1]            : com.xebialabs.deployit.engine.api.dto.Deployment
converter-type[1]   : com.xebialabs.xltype.serialization.xstream.DeploymentConverter
version             : not available
-------------------------------
	at org.jboss.resteasy.client.core.BaseClientResponse.readFrom(BaseClientResponse.java:483)
	at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:396)
	at org.jboss.resteasy.client.core.BaseClientResponse.getEntity(BaseClientResponse.java:367)
	at org.jboss.resteasy.client.core.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:75)
	at com.xebialabs.deployit.booter.remote.resteasy.DeployitBodyEntityExtractor.extractEntity(DeployitBodyEntityExtractor.java:27)
	at org.jboss.resteasy.client.core.ClientInvoker.invoke(ClientInvoker.java:138)
	at org.jboss.resteasy.client.core.ClientProxy.invoke(ClientProxy.java:98)
	at com.sun.proxy.$Proxy127.prepareAutoDeployeds(Unknown Source)
	at com.xebialabs.deployit.ci.server.DeployCommand.deploy(DeployCommand.java:108)
	at com.xebialabs.deployit.ci.server.DeployitServerImpl.deploy(DeployitServerImpl.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.xebialabs.deployit.ci.server.PluginFirstClassloaderInvocationHandler.doInvoke(PluginFirstClassloaderInvocationHandler.java:70)
	at com.xebialabs.deployit.ci.server.PluginFirstClassloaderInvocationHandler.invoke(PluginFirstClassloaderInvocationHandler.java:56)
Caused: hudson.remoting.ProxyException: com.xebialabs.deployit.ci.DeployitPluginException: org.jboss.resteasy.spi.ReaderException: com.thoughtworks.xstream.converters.ConversionException: DescriptorRegistry does not know about type [smoketest.ExecutedHttpRequestTest] : DescriptorRegistry does not know about type [smoketest.ExecutedHttpRequestTest]
---- Debugging information ----
message             : DescriptorRegistry does not know about type [smoketest.ExecutedHttpRequestTest]
cause-exception     : java.lang.IllegalArgumentException
cause-message       : DescriptorRegistry does not know about type [smoketest.ExecutedHttpRequestTest]
class               : com.xebialabs.deployit.plugin.api.udm.ConfigurationItem
required-type       : com.xebialabs.deployit.plugin.api.udm.ConfigurationItem
converter-type      : com.xebialabs.deployit.booter.remote.xml.RemoteXStreamCiConverter
path                : /deployment/deployeds/smoketest.ExecutedHttpRequestTest
line number         : 16
class[1]            : com.xebialabs.deployit.engine.api.dto.Deployment
converter-type[1]   : com.xebialabs.xltype.serialization.xstream.DeploymentConverter
version             : not available
-------------------------------
	at com.xebialabs.deployit.ci.server.PluginFirstClassloaderInvocationHandler.invoke(PluginFirstClassloaderInvocationHandler.java:60)
	at com.sun.proxy.$Proxy97.deploy(Unknown Source)
	at com.xebialabs.deployit.ci.workflow.XLDeployDeployStep$XLDeployPublishExecution.run(XLDeployDeployStep.java:101)
	at com.xebialabs.deployit.ci.workflow.XLDeployDeployStep$XLDeployPublishExecution.run(XLDeployDeployStep.java:77)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

My manifest looks like
```
<smoketest.HttpRequestTest name="/spring-petclinic-smoke-test">
      <tags />
      <netscalerServiceGroup>{{NETSCALER_SERVICE_GROUP}}</netscalerServiceGroup>
      <netscalerServiceGroupName>{{NETSCALER_SERVICE_GROUP_NAME}}</netscalerServiceGroupName>
      <netscalerServiceGroupPort>{{NETSCALER_SERVICE_GROUP_PORT}}</netscalerServiceGroupPort>
      <url>{{petclinic.smoke.test.url}}</url>
      <expectedResponseText>PetClinic :: a Spring Framework demonstration</expectedResponseText>
      <unexpectedResponseText>Error 404--Not Found</unexpectedResponseText>
      <headers />
    </smoketest.HttpRequestTest>
```
My pipelinestep looks like:
```
    stage ('spring-petclinic-weblogic-12c-pipeline - deploy application') {
      /* Deploy application to environmet in XL Deploy */
      steps {
        xldDeploy environmentId: 'Environments/TPE/O/Petclinic-Weblogic12c-pipeline-O/Petclinic-Weblogic12c-pipeline-O',
           packageId: 'Applications/TPE/Petclinic-Weblogic12c-pipeline/Petclinic-Weblogic12c-pipeline/2.1.0-SNAPSHOT',
           serverCredentials: 'XL Deploy deployment user TPE'
      }
    }
```

What do i have to do to solve this ?
Deploying manual from inside the GUI works fine.

**Comment by kdeenkhoorn** [comment]
Issue can be closed.
